// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajeiycyvfwzcwmamwkqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqZWl5Y3l2Znd6Y3dtYW13a3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxMjY1MDEsImV4cCI6MjA0OTcwMjUwMX0.zuszqJ6JDc3XRCNaZQgSkxR6x-IHxHgMlZMwOaDsXX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);